### ISSUE TITLE
rustic gives the error: Err` value: HexError(OddLength)', src/backend/local.rs:77:68

### ISSUE THREAD

**Issue by borkd** [rustic-rs/rustic#37]
This is the stack trace with #36 merged (issue #35, already closed). While the run for #35 was against a live filesystem, this instance rustic is forced to run against a read-only filesystem snapshot. This path passes `restic -r rrepo-master-v2-snap/ check --no-lock`

restic
```
./restic-master -r rrepo-master-v2-snap/ check --no-lock -vv
using temporary cache in /tmp/restic-check-cache-1350556230
enter password for repository:
repository 55b1eb2a opened (repo version 2) successfully, password is correct
created new cache in /tmp/restic-check-cache-1350556230
load indexes
check all packs
check snapshots, trees and blobs
[7:33] 100.00%  58 / 58 snapshots
no errors were found
```

rustic:
```
RUST_BACKTRACE=full ./rustic-rs -r rrepo-master-v2-snap/ check
enter repository password:
password is correct
checking packs in index and from pack list...
- reading index...
[00:00:03] ████████████████████████████████████████         69/69                                                                                                                                                             - listing packs...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: HexError(OddLength)', src/backend/local.rs:77:68
stack backtrace:
   0:     0x64a623c4d70d - std::backtrace_rs::backtrace::libunwind::trace::hb729d9642bb971eb
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x64a623c4d70d - std::backtrace_rs::backtrace::trace_unsynchronized::h373bb774579df5c7
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x64a623c4d70d - std::sys_common::backtrace::_print_fmt::hfbd4e92d240c89bb
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x64a623c4d70d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8f618991fbf64972
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x64a623c70ddc - core::fmt::write::hc69b5b640d88cce8
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/fmt/mod.rs:1196:17
   5:     0x64a623c47571 - std::io::Write::write_fmt::h3403cef06a24a303
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/io/mod.rs:1654:15
   6:     0x64a623c4ef25 - std::sys_common::backtrace::_print::h368f27cdedea0e52
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x64a623c4ef25 - std::sys_common::backtrace::print::ha105c9cf5a64cd17
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x64a623c4ef25 - std::panicking::default_hook::{{closure}}::h48ed2c3707d5e20e
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:295:22
   9:     0x64a623c4eb99 - std::panicking::default_hook::h8744fc5cea5e3110
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:314:9
  10:     0x64a623c4f4f8 - std::panicking::rust_panic_with_hook::hc82286af2030e925
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:698:17
  11:     0x64a623c4f3a7 - std::panicking::begin_panic_handler::{{closure}}::h1c15057c2f09081f
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:588:13
  12:     0x64a623c4dbc4 - std::sys_common::backtrace::__rust_end_short_backtrace::h65de906a5330f8da
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x64a623c4f0d9 - rust_begin_unwind
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
  14:     0x64a6236a8b83 - core::panicking::panic_fmt::h741cfbfc95bc6112
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
  15:     0x64a6236a8c73 - core::result::unwrap_failed::h995262f85f9c4e2c
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1785:5
  16:     0x64a623783159 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::hd7ea5ea3eae70fb0
  17:     0x64a6236c8bb2 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h8f2c55a31a198b9d
  18:     0x64a6236d4209 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h8762486d8da13cfb
  19:     0x64a6237bb960 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h40a73bfb7dcaad5b
  20:     0x64a6237cbf29 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hdca1308cc21a58f5
  21:     0x64a6237bed0d - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h5b066d80e805c525
  22:     0x64a6237eed36 - rustic_rs::commands::execute::{{closure}}::h2d8eac611ebf7679
  23:     0x64a6237bb26d - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h3d0482824ccc2c38
  24:     0x64a62378fabd - std::thread::local::LocalKey<T>::with::h8c4b741e4425a44f
  25:     0x64a6236e81ba - tokio::park::thread::CachedParkThread::block_on::ha865f4ee00444c1b
  26:     0x64a62370b7cd - tokio::runtime::thread_pool::ThreadPool::block_on::haf56b5342415c866
  27:     0x64a62372ffcb - tokio::runtime::Runtime::block_on::h8333755947d7437e
  28:     0x64a62370dc8a - rustic_rs::main::h5ee36d2599f6e96b
  29:     0x64a6236d7c83 - std::sys_common::backtrace::__rust_begin_short_backtrace::hcedd0aca8c9a1910
  30:     0x64a6236fd2fd - std::rt::lang_start::{{closure}}::h311ae3624bbdb5f7
  31:     0x64a623c406fe - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf833e7144973d4be
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:280:13
  32:     0x64a623c406fe - std::panicking::try::do_call::h79761d203bfb6b46
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
  33:     0x64a623c406fe - std::panicking::try::h0561cbbe1722251d
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
  34:     0x64a623c406fe - std::panic::catch_unwind::hbca347ddd031b141
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
  35:     0x64a623c406fe - std::rt::lang_start_internal::{{closure}}::h0492050ad281ec32
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/rt.rs:128:48
  36:     0x64a623c406fe - std::panicking::try::do_call::h3ebce69871996bb3
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
  37:     0x64a623c406fe - std::panicking::try::hbed537d20e728475
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
  38:     0x64a623c406fe - std::panic::catch_unwind::h4185e2024c6a5d05
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
  39:     0x64a623c406fe - std::rt::lang_start_internal::h1899cfd715ca6829
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/rt.rs:128:20
  40:     0x64a62370dd62 - main
  41:     0x720bf251a2e1 - __libc_start_main
  42:     0x64a6236a8e2a - _start
  43:                0x0 - <unknown>
```

**Comment by aawsome** [comment]
Thanks for reporting! 
This error comes from the fact that there is a file in your repo which is not a valid repository file.

repository files should be either
- 64 characters long and a valid hex representation of a 256bit hex value, or
- the config file

Can you use `find rrepo-master-v2-snap/ -type f` to check if you have additional files?

However, you are right, the error handling is a bug here. I'm just not perfectly sure what to do:
- simply ignore additional files
- ignore additional files but print a warning
- abort with a nice error message

If you have a preference, please tell me!

**Comment by aawsome** [comment]
Having thought about it, to abort is really the worst idea. I made #38 which silently ignores non-hex-filename files.
If we need the `--pedantic` option, this should be tackled in a separate feature request.

@borkd can you test if #38 works for you?

**Comment by borkd** [comment]
yes, now it does
